FROM ubuntu:22.04

# Avoid interactive prompts during install
#ENV DEBIAN_FRONTEND=noninteractive

RUN add-apt-repository ppa:ansible/ansible

# Install essential tools
RUN apt update && \
    apt install -y \
        sudo \
        openssh-client \
        iputils-ping \
        net-tools \
        curl \
        wget \
        git \
        vim \
        less \
        gnupg2 \
        software-properties-common \
        ansible && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Add a non-root user (optional but common)
RUN useradd -ms /bin/bash dev && \
    echo "dev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to non-root user by default
USER dev
WORKDIR /home/dev